opt_in_rules:
  - closure_body_length
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_optional_boolean
  - empty_xctest_method
  - enum_case_associated_values_count
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_types_order
  - function_default_parameter_at_end
  - identical_operands
  - implicitly_unwrapped_optional
  - let_var_whitespace
  - optional_enum_case_matching
  - override_in_extension
  - prefer_self_type_over_type_of_self
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - type_contents_order
  - unavailable_function
  - unowned_variable_capture
  - unused_declaration
excluded:
  - Build
  - Carthage
  - DerivedData
  - fastlane
  - Pods
  - WUPTestTests/Generated

closing_brace:
  severity: error
closure_parameter_position:
  severity: error
colon:
  severity: error
comma:
  severity: error
control_statement:
  severity: error
cyclomatic_complexity:
  warning: 6
  error: 8
deployment_target:
  severity: error
empty_enum_arguments:
  severity: error
empty_parameters:
  severity: error
empty_parentheses_with_trailing_closure:
  severity: error
file_length:
  warning: 300
  error: 400
for_where:
  severity: error
function_body_length:
  warning: 20
  error: 30
function_parameter_count:
  warning: 3
  error: 8
identifier_name:
  min_length: 2
  severity: error
implicit_getter:
  severity: error
inert_defer:
  severity: error
is_disjoint:
  severity: error
large_tuple:
  warning: 4
  error: 6
leading_whitespace:
  severity: error
legacy_cggeometry_functions:
  severity: error
legacy_constant:
  severity: error
legacy_constructor:
  severity: error
legacy_hashing:
  severity: error
legacy_nsgeometry_functions:
  severity: error
line_length:
  warning: 150
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
mark:
  severity: error
nesting:
  severity: error
no_space_in_method_call:
  severity: error
opening_brace:
  severity: error
operator_whitespace:
  severity: error
orphaned_doc_comment:
  severity: error
private_over_fileprivate:
  severity: error
protocol_property_accessors_order:
  severity: error
reduce_boolean:
  severity: error
redundant_discardable_let:
  severity: error
redundant_objc_attribute:
  severity: error
redundant_optional_initialization:
  severity: error
redundant_set_access_control:
  severity: error
redundant_string_enum_value:
  severity: error
redundant_void_return:
  severity: error
return_arrow_whitespace:
  severity: error
shorthand_operator:
  severity: error
statement_position:
  severity: error
switch_case_alignment:
  severity: error
syntactic_sugar:
  severity: error
trailing_comma:
  severity: error
trailing_newline:
  severity: error
trailing_semicolon:
  severity: error
trailing_whitespace:
  severity: error
type_name:
  severity: error
unneeded_break_in_switch:
  severity: error
unused_capture_list:
  severity: error
unused_closure_parameter:
  severity: error
unused_control_flow_label:
  severity: error
unused_enumerated:
  severity: error
unused_optional_binding:
  severity: error
unused_setter_value:
  severity: error
valid_ibinspectable:
  severity: error
vertical_parameter_alignment:
  severity: error
vertical_whitespace:
  severity: error
void_return:
  severity: error
weak_delegate:
  severity: error
